[project]
name = "jit"
version = "0.1.0"
description = "Git helper tool for commit message organisation and demystifying common version-control-related scenarios."
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
jit = "jit.cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"